name: PermsToggle
main: net.q_silver.kjperms.permstoggle.PermsToggle
version: 0.0.1
commands:
  wgo:
    description: Toggle WorldGuard Override
    usage: /wgo
    permission: permstoggle.wgo
    permission-message: Sorry, you can't do that!